name: Build
on: [push]

jobs:
  lint:
    name:  Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run lint
  build:
    name: 🛠 Build
    runs-on: ubuntu-latest
    # This job will only run if both `test` and `lint` jobs run successfully.
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build     
      
